#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5D2EEE6F6F349D7C (tim@centricular.com)
#
Name     : gst-plugins-ugly
Version  : 1.14.4
Release  : 14
URL      : https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.14.4.tar.xz
Source0  : https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.14.4.tar.xz
Source99 : https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.14.4.tar.xz.asc
Summary  : Streaming media framework, ugly plugins, uninstalled
Group    : Development/Tools
License  : LGPL-2.1
Requires: gst-plugins-ugly-lib = %{version}-%{release}
Requires: gst-plugins-ugly-license = %{version}-%{release}
Requires: gst-plugins-ugly-locales = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires : valgrind

%description
GStreamer 1.13.x development series
WHAT IT IS
----------
This is GStreamer, a framework for streaming media.

%package doc
Summary: doc components for the gst-plugins-ugly package.
Group: Documentation

%description doc
doc components for the gst-plugins-ugly package.


%package lib
Summary: lib components for the gst-plugins-ugly package.
Group: Libraries
Requires: gst-plugins-ugly-license = %{version}-%{release}

%description lib
lib components for the gst-plugins-ugly package.


%package license
Summary: license components for the gst-plugins-ugly package.
Group: Default

%description license
license components for the gst-plugins-ugly package.


%package locales
Summary: locales components for the gst-plugins-ugly package.
Group: Default

%description locales
locales components for the gst-plugins-ugly package.


%prep
%setup -q -n gst-plugins-ugly-1.14.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547489544
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1547489544
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gst-plugins-ugly
cp COPYING %{buildroot}/usr/share/package-licenses/gst-plugins-ugly/COPYING
%make_install
%find_lang gst-plugins-ugly-1.0

%files
%defattr(-,root,root,-)

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/ch01.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/ch02.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-1.0.devhelp2
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-a52dec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-amrnbdec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-amrnbenc.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-amrwbdec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-cdiocddasrc.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-a52dec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-amrnb.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-amrwbdec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-asf.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-cdio.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-dvdlpcmdec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-dvdread.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-dvdsub.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-mpeg2dec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-realmedia.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-sid.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-x264.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-plugin-xingmux.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-rademux.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-rdtmanager.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-rmdemux.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-rtspreal.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-rtspwms.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-siddec.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-x264enc.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/gst-plugins-ugly-plugins-xingmux.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/home.png
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/index.html
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/left-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/left.png
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/right-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/right.png
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/style.css
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/up-insensitive.png
/usr/share/gtk-doc/html/gst-plugins-ugly-plugins-1.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/gstreamer-1.0/libgstasf.so
/usr/lib64/gstreamer-1.0/libgstdvdlpcmdec.so
/usr/lib64/gstreamer-1.0/libgstdvdsub.so
/usr/lib64/gstreamer-1.0/libgstrealmedia.so
/usr/lib64/gstreamer-1.0/libgstxingmux.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gst-plugins-ugly/COPYING

%files locales -f gst-plugins-ugly-1.0.lang
%defattr(-,root,root,-)

